# Generated by Django 2.0.7 on 2018-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
