# Generated by Django 2.0.7 on 2018-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberapi', '0003_auto_20180729_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcab',
            name='booking_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
