# Generated by Django 2.0.7 on 2018-07-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberapi', '0004_auto_20180729_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcab',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cust_id', to='uberapi.Customer'),
        ),
        migrations.AlterField(
            model_name='bookcab',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cust_name', to='uberapi.Customer'),
        ),
        migrations.AlterField(
            model_name='bookcab',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_driver_id', to='uberapi.Driver'),
        ),
        migrations.AlterField(
            model_name='bookcab',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_driver_name', to='uberapi.Driver'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_book_id', to='uberapi.BookCab'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_cust_id', to='uberapi.Customer'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_cust_name', to='uberapi.Customer'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_driver_id', to='uberapi.Driver'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_driver_name', to='uberapi.Driver'),
        ),
    ]
